### ISSUE TITLE
X32 DCA 

### ISSUE THREAD

**Issue by olauzzon** [bitfocus/companion-module-x32#2]
Cant control the DCA groups on my X32.

**Comment by jakenjones** [comment]
Same here. Besides not being able to control DCAs, I also cannot call cues or snippets. I can call scenes and control tape operation and channels. I haven't tried the other options, yet because we don't really need control over them in Companion. It seems that it sends the commands and I do not see any errors in Companion.

**Comment by jakenjones** [comment]
I found the issue for the DCAs. The structure is not correct.
DCA Mute:
Path - /dca/[1...8]/on
Value - ON

DCA Unmute:
Path - /dca/[1...8]/on
Value - OFF

DCA fader level:
Path - /dca/[1...8]/fader/
Value - [-oo, -90.0...10.0]

DCA label:
Path - /dca/[1...8]/config/name
Value: [text]

DCA icon:
Path - /dca/[1...8]/config/icon
Value - [1...74]

DCA color:
Path - /dca/[1...8]/config/color
Value - [OFF, RD, GN, YE, BL, MG, CY, WH, OFFi, RDi, GNi, YEi, BLi, MGi, CYi, WHi]

**Comment by TaylorTMusic** [comment]
I found that the x32 wants a floating point integer for the DCA fader level.

Sending a general OSC float with: /dca/1/fader and a number works for now and it how I'm controlling my board.

**Comment by PerRoine** [comment]
The DCA error have been fixed as noted it was a error in the Path for Fader and Mute
